# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d449865c4291377f3963283e1bf67b27664a15b88dd3e4966a24451c25181f40864ff7848c92e17d3b28bcf0e6d1849760ccaf2aa58554b26dd356404fc3d7

test:
  secret_key_base: de324a62fa6263cff9d29ed66bfc5314e14c50536ab7559b733e1bf4bc239861224f350651993c0657a618f279517369188cc1b94fd07a72ae917750c310a3a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
